### ISSUE TITLE
Random Walk does not work properly with the Tor Browser 6.5

### ISSUE THREAD

**Issue by dstruck** [demonfiddler/random-walk#2]
Random Walk does not work properly in the Tor Browser 6.5 (based on Mozilla Firefox 45.7.0). The icon of the extension is not shown in the toolbar. The default BBC start page is loaded in a new tab but no link is being followed after that.

**Comment by demonfiddler** [comment]
The inability to follow links may be imposed by the built-in security restrictions of the TOR browser. I'm not sure why the toolbar icon doesn't show up; again, this could be standard TOR behaviour. TOR is a pretty specialised application so I probably won't spend much time investigating this.

**Comment by dstruck** [comment]
It might due to an undefined variable: **TypeError: tabs[(tabs.length - 1)]**. I get this error message when I start the Tor Browser from the command line:

>console.info: random-walk: main.js
console.info: random-walk: createToggleButton
console.info: random-walk:   accept, Content-Language: en-GB, url: http://www.bbc.co.uk/news/
console.error: random-walk: 
  Message: TypeError: tabs[(tabs.length - 1)] is undefined
  Stack:
    init@resource://xxx/lib/main.js:270:3
@resource://xxx/lib/main.js:229:2
run@resource://gre/modules/commonjs/sdk/addon/runner.js:147:19
startup/</<@resource://gre/modules/commonjs/sdk/addon/runner.js:87:9
Handler.prototype.process@resource://gre/modules/Promise-backend.js:933:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise-backend.js:812:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise-backend.js:746:1
